name: Run Selected Playwright Test Suites

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm ci

      - name: Install Playwright browsers
        run: npx playwright install --with-deps

      - name: Start backend server
        run: |
          nohup npm start &
          sleep 5

      - name: Run only suite files
        run: |
          npx playwright test tests/api/api-testSuite.spec.ts
          npx playwright test tests/ui/ui-testSuite.spec.ts

